const { DateTime } = require('../index')
let datetime = new DateTime()
// console.log('format', new Date().format('yyyy-MM-dd hh:mm:ss'))
// console.log('prev', new Date().prev(1e3 * 60 * 60 * 24))
// console.log('prevDay', new Date().prevDay({ day: 5 }))
// console.log('prevDay', new Date().prevDay({ day: 90, isShowAll: true }))
// console.log('prevDay', new Date().prevDay({ day: 5, isShowAll: true, includeCurrent: true }))
// console.log('prevMonth', new Date('2023-07-31 16:33:00').prevMonth({ month: 5, includeCurrent: false, isShowAll: true }))
// console.log('prevYear', new Date().prevYear({ year: 5, includeCurrent: false, isShowAll: true }))
// console.log('next', new Date().next(1e3 * 60 * 60 * 24))
// console.log('nextDay', new Date().nextDay({ day: 5 }))
// console.log('nextDay', new Date().nextDay({ day: 5, isShowAll: true }))
// console.log('nextDay', new Date().nextDay({ day: 5, isShowAll: true, includeCurrent: true }))
// console.log('nextMonth', new Date().nextMonth({ month: 5, includeCurrent: false, isShowAll: true }))
// console.log('nextYear', new Date().nextYear({ year: 5, includeCurrent: true, isShowAll: true }))
// console.log('split', datetime.split({ startTime: new Date('2022-01-01 00:00:00'), endTime: new Date('2022-01-10 23:59:59'), gap: 1e3 * 60 * 60 * 24 }))
// console.log(datetime.calc({ startTime: new Date('2022-01-01 00:00:00'), endTime: new Date('2022-11-10 23:59:59') }))
// console.log(datetime.calc({ startTime: new Date('2022-01-01 00:00:00'), endTime: new Date('2022-11-10 23:59:59') ,type : 'day'}))
// console.log(new Date().getWeek())
// console.log(new Date().getWeek(['周日', '周一', '周二', '周三', '周四', '周五', '周六']))
// console.log(new Date().getRangeYear())
// console.log(new Date().getRangeMonth())
// console.log(new Date().getRangeWeek())