const { EasyArray } = require('../index')
new EasyArray()
// console.log([1, 2, 3, 4, 5, 1, 3, 4].unique())
// console.log([{ a: 1 }, { b: 2 }, { a: 2 }, { a: 3 }, { a: 1 }, { b: 2 }, { b: 1 }, { c: 1 }].unique('a'))
// console.log([1, 2, 3, 4, 5, 6, 7].groupByLength(2))
// console.log([{ a: 1 }, { b: 2 }, { a: 2 }, { a: 3 }, { a: 1 }, { b: 2 }, { b: 1 }, { c: 1 }].groupByName('c'))
console.log([{ a: 1 }, { b: 2 }, { a: 2 }, { a: 3 }, { a: 1 }, { b: 2 }, { b: 1 }, { c: 1 }].groupByValue('a'))
